/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/55_Cancri_e_1_24364.glb --transform 
Files: ./public/55_Cancri_e_1_24364.glb [10.41MB] > C:\Me\ExoPlanets\55_Cancri_e_1_24364-transformed.glb [134.04KB] (99%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/55_Cancri_e_1_24364-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube008.geometry} material={materials['Default OBJ.005']} />
    </group>
  )
}

useGLTF.preload('/55_Cancri_e_1_24364-transformed.glb')
