export const planets = [
  {
    name: "Kepler-22b",
    description: "A potentially habitable super-Earth.",
    distance: "635 light years",
    type: "Super Earth",
    planetRadius: 2.1,
    DiscoveryMethod: "Transit",
    planetMass: 9.1,
    OrbitalPeriod: 11.2,
    DiscoveryDate: "2011",
    modelPath: "/models/kepler-22b.glb",
  },
  {
    name: "Proxima Centauri b",
    description: "The closest known exoplanet to Earth.",
    distance: "4 light years",
    type: "Super Earth",
    planetRadius: 1.03,
    DiscoveryMethod: "Radial Velocity",
    planetMass: 1.07,
    OrbitalPeriod: 11.2,
    DiscoveryDate: "2016",
    modelPath: "/models/Proxima_b_1_13776.glb",
  },
  {
    name: "Kepler - 452b",
    description: "A gas giant with extreme weather conditions.",
    distance: "1,799 light years",
    type: "Super Earth",
    planetRadius: 1.63,
    DiscoveryMethod: "Transit",
    planetMass: 3.29,
    OrbitalPeriod: 384.8,
    DiscoveryDate: "2015",
    modelPath: "/models/kepler_-_452b_planet.glb",
  },
];
